[package]
name = "cicada-client"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
cicada-core = { path = "../../cicada-core" }
cicada-api = { path = "../../cicada-api" }
serde_json.workspace = true
serde.workspace = true
tauri = { version = "1", features = ["shell-open", "process-command-api", "updater", "system-tray"] }
tokio.workspace = true
uuid.workspace = true
dirs = "5"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
